/*
====================================================================================================================================================================================
WREL111 -  Notas de Entrada - Conferencia Produto x XML
====================================================================================================================================================================================
Historico de alteracoes
====================================================================================================================================================================================
16/01/2025 - WILLIAM
	- Conversão do script SQL para StoredProcedure;
	- Inclusão do @empcod nos parametros de entrada da SP;	
	- Uso da SP "usp_GetCodigosProdutos" para obter os codigos dos produtos;
	- Retirada das linhas de codigo, sem uso:
		SET @UTEL = (SELECT dbo.FCNDIASUTEIS(@Date_De,@Date_Ate))
		SET @DEV = (SELECT RTRIM(LTRIM(PARVAL)) FROM TBS025 WHERE PARCHV = 1330)
************************************************************************************************************************************************************************************
*/
--CREATE PROCEDURE [dbo].[usp_RS_NotasEntradaConferenciaProdutoxXML]
ALTER PROCEDURE [dbo].[usp_RS_NotasEntradaConferenciaProdutoxXML]
	@empcod smallint,
	@dateDe datetime,
	@dateAte datetime,
	@dataEmissaoDe datetime,
	@dataEmissaoAte datetime,
	@dataEntradaDe datetime,
	@dataEntradaAte datetime,
	@TipoNota varchar(50),
	@NumeroNF int,
	@CodigoProdutoSistema varchar(15),
	@DescricaoSistema varchar(60),
	@CodigoProdutoXML varchar(60),
	@DescricaoXML varchar(200),
	@CodigoClienteFornecedor int,
	@NomeClienteFornecedor varchar(60),
	@MovimentouEstoque varchar(10),
	@Cancelado varchar(10),
	@Efetivado char(1)
AS
BEGIN
	SET NOCOUNT ON;
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	DECLARE @codigoEmpresa smallint, 
			@Date_De datetime, @Date_Ate datetime, 	@DataEmissao_De datetime, @DataEmissao_Ate datetime, @DataEntrada_De datetime, @DataEntrada_Ate datetime, @TiposNota varchar(50),
			@NFENUM int, @PROCOD varchar(15), @PRODES varchar(60), @CodigoProduto_XML varchar(60), @Descricao_XML varchar(200), @NFECOD int, @NFENOM varchar(60), @MovEstoque varchar(10),
			@Cancelados varchar(10), @SeEfetivado char(1), @QuantidadeNotas int, @ValorTotalNotas decimal(20,4);

-- Desativando a detecção de parâmetros(Parameter Sniffing)
	SET @codigoEmpresa = @empcod;
	SET @Date_De = (SELECT ISNULL(@dateDe, '17530101'));
	SET @Date_Ate = (SELECT ISNULL(@Date_Ate, GETDATE()));
	SET @DataEmissao_De = (SELECT ISNULL(@dataEmissaoDe, '17530101'));
	SET @DataEmissao_Ate = (SELECT ISNULL(@dataEmissaoAte, GETDATE()));
	SET @DataEntrada_De = (SELECT ISNULL(@dataEntradaDe, '17530101'));
	SET @DataEntrada_Ate = (SELECT ISNULL(@dataEntradaAte, GETDATE()));
	SET @TiposNota = @TipoNota;
	SET @NFENUM = @NumeroNF;
	SET @PROCOD = @CodigoProdutoSistema;
	SET @PRODES = @DescricaoSistema;
	SET @CodigoProduto_XML = RTRIM(LTRIM(@CodigoProdutoXML));
	SET @Descricao_XML = RTRIM(LTRIM(@DescricaoXML));
	SET @NFECOD = @CodigoClienteFornecedor;
	SET @NFENOM = RTRIM(LTRIM(UPPER(@NomeClienteFornecedor)));
	SET @MovEstoque = @MovimentouEstoque;
	SET @Cancelados = @Cancelado;
	SET @SeEfetivado = @Efetivado;
		
-- Uso da funcao split, para as clausulas IN()
	-- Tipos de notas
	IF object_id('TempDB.dbo.#TIPOSNOTA') IS NOT NULL
		DROP TABLE #TIPOSNOTA;
	SELECT 
		elemento as valor
	INTO #TIPOSNOTA FROM fSplit(@TiposNota, ',');
	-- Movimentacao de estoque
	IF object_id('TempDB.dbo.#MOVEST') IS NOT NULL
		DROP TABLE #MOVEST;
	SELECT 
		elemento as valor
	INTO #MOVEST FROM fSplit(@MovEstoque, ',');
	-- Cancelado
	IF object_id('TempDB.dbo.#CANCEL') IS NOT NULL
		DROP TABLE #CANCEL;
	SELECT 
		elemento as valor
	INTO #CANCEL FROM fSplit(@Cancelados, ',');

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	-- Obtem códigos dos produtos conforme filtro utilizando a SP

	IF object_id('tempdb.dbo.#CodigosProduto') IS NOT NULL
		DROP TABLE #CodigosProduto;	
	
	CREATE TABLE #CodigosProduto (PROCOD varchar(15))

	INSERT INTO #CodigosProduto
	EXEC usp_GetCodigosProdutos @codigoEmpresa, @PROCOD, @PRODES, 0, ''

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	-- SELECT DISTINCT SUBSTRING(NFECFOP,3,4) FROM TBS0591
	-- SELECT * FROM TBS0591 WHERE SUBSTRING(NFECFOP,3,4) = '108'
	-- ENTRADA

	IF object_id('tempdb.dbo.#NFECFOP') IS NOT NULL
		DROP TABLE #NFECFOP;	
   
	CREATE TABLE #NFECFOP (NFECFOP char(3), NFECFOPDES varchar(45))

	INSERT INTO #NFECFOP VALUES ('102' , 'COMPRA PARA COMERCIALIZACAO')
	INSERT INTO #NFECFOP VALUES ('117' , 'COMPRA FUTURA (MERCADORIA)')
	INSERT INTO #NFECFOP VALUES ('122' , 'COMPRA PARA INDUSTRIALIZACAO')
	INSERT INTO #NFECFOP VALUES ('152' , 'TRANSFERENCIA PARA COMERCIALIZACAO')
	INSERT INTO #NFECFOP VALUES ('201' , 'DEVOLUCAO DE VENDA (INDUSTRIALIZADO)')
	INSERT INTO #NFECFOP VALUES ('202' , 'DEVOLUCAO DE VENDA')
	INSERT INTO #NFECFOP VALUES ('253' , 'ENERGIA (ESTABELECIMENTO COMERCIAL)')
	INSERT INTO #NFECFOP VALUES ('403' , 'COMPRA PARA COMERCIALIZACAO ST')
	INSERT INTO #NFECFOP VALUES ('407' , 'USO E CONSUMO (ST)')
	INSERT INTO #NFECFOP VALUES ('408' , 'TRANSFERENCIA PARA INDUSTRIALIZACAO')
	INSERT INTO #NFECFOP VALUES ('409' , 'TRANSFERENCIA PARA COMERCIALIZACAO ST')
	INSERT INTO #NFECFOP VALUES ('411' , 'DEVOLUCAO DE VENDA ST')
	INSERT INTO #NFECFOP VALUES ('551' , 'COMPRA BEM ATIVO IMOBILIZADO')
	INSERT INTO #NFECFOP VALUES ('552' , 'TRANSFERENCIA DE BEM DO ATIVO IMOBILIZADO')
	INSERT INTO #NFECFOP VALUES ('556' , 'USO E CONSUMO (COMPRA)')
	INSERT INTO #NFECFOP VALUES ('557' , 'USO E CONSUMO (TRANSFERENCIA)')
	INSERT INTO #NFECFOP VALUES ('653' , 'COMBUSTIVEL')
	INSERT INTO #NFECFOP VALUES ('907' , 'REMESSA')
	INSERT INTO #NFECFOP VALUES ('908' , 'ENTRADA DE BEM COMODATO') -- Entrada de bem por conta de contrato de comodato
	INSERT INTO #NFECFOP VALUES ('910' , 'BONIFICACAO')
	INSERT INTO #NFECFOP VALUES ('911' , 'AMOSTRA')
	INSERT INTO #NFECFOP VALUES ('913' , 'DEMONSTRACAO')
	INSERT INTO #NFECFOP VALUES ('916' , 'RETORNO DE CONSERTO OU REPARO')
	INSERT INTO #NFECFOP VALUES ('917' , 'CONSIGNAÇÃO') -- Entrada de mercadoria recebida em consignação mercantil ou industrial
	INSERT INTO #NFECFOP VALUES ('918' , 'DEVOLUÇÃO CONSIGNAÇÃO') -- Devolução de mercadoria remetida em consignação mercantil ou industrial
	INSERT INTO #NFECFOP VALUES ('919' , 'DEVOLUCAO SIMBOLICA')
	INSERT INTO #NFECFOP VALUES ('922' , 'COMPRA FUTURA (FATURAMENTO)')
	INSERT INTO #NFECFOP VALUES ('923' , 'REMESSA A ORDEM')
	INSERT INTO #NFECFOP VALUES ('933' , 'AQUISICAO DE SERVICO')
	INSERT INTO #NFECFOP VALUES ('949' , 'OUTRAS ENTRADAS')

	-- SELECT * FROM #NFECFOP

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	-- SAIDA 

	IF object_id('tempdb.dbo.#NFECFOPXML') IS NOT NULL
		DROP TABLE #NFECFOPXML;	
   
	CREATE TABLE #NFECFOPXML (NFECFOPXML char(3), NFECFOPDES varchar(45))

	INSERT INTO #NFECFOPXML VALUES ('101' , 'VENDA INDUSTRIALIZADO (IPI)')
	INSERT INTO #NFECFOPXML VALUES ('102' , 'VENDA DE PRODUTOS SEM ST')
	INSERT INTO #NFECFOPXML VALUES ('103' , 'VENDA DE PRODUTOS FORA DO ESTABELICIMENTO')
	INSERT INTO #NFECFOPXML VALUES ('105' , 'VENDA DE PRODUTOS EM DEPOSITO (IPI)')
	INSERT INTO #NFECFOPXML VALUES ('106' , 'VENDA DE PRODUTOS EM DEPOSITO')
	INSERT INTO #NFECFOPXML VALUES ('116' , 'VENDA FUTURA (MERCADORIA) (IPI)')
	INSERT INTO #NFECFOPXML VALUES ('117' , 'VENDA FUTURA (MERCADORIA)')
	INSERT INTO #NFECFOPXML VALUES ('118' , 'VENDA DE PRODUTOS A ORDEM (IPI)')
	INSERT INTO #NFECFOPXML VALUES ('119' , 'VENDA DE PRODUTOS A ORDEM')
	INSERT INTO #NFECFOPXML VALUES ('152' , 'TRANSFERENCIA PARA COMERCIALIZACAO')
	INSERT INTO #NFECFOPXML VALUES ('202' , 'DEVOLUCAO DE COMPRA')
	INSERT INTO #NFECFOPXML VALUES ('401' , 'VENDA DE PRODUTOS ST (IPI)')
	INSERT INTO #NFECFOPXML VALUES ('402' , 'VENDA DE PRODUTOS ST (IPI)')
	INSERT INTO #NFECFOPXML VALUES ('403' , 'VENDA DE PRODUTOS ST')
	INSERT INTO #NFECFOPXML VALUES ('404' , 'VENDA DE PRODUTOS SEM ST (JA RETIDO)')
	INSERT INTO #NFECFOPXML VALUES ('405' , 'VENDA DE PRODUTOS SEM ST (SUBSTITUIDO)')
	INSERT INTO #NFECFOPXML VALUES ('409' , 'TRANSFERENCIA PARA COMERCIALIZACAO ST')
	INSERT INTO #NFECFOPXML VALUES ('557' , 'USO E CONSUMO (TRANSFERENCIA)')
	INSERT INTO #NFECFOPXML VALUES ('656' , 'COMBUSTIVEL')
	INSERT INTO #NFECFOPXML VALUES ('910' , 'BONIFICACAO')
	INSERT INTO #NFECFOPXML VALUES ('911' , 'AMOSTRA')
	INSERT INTO #NFECFOPXML VALUES ('912' , 'DEMONSTRACAO')
	INSERT INTO #NFECFOPXML VALUES ('913' , 'DEMONSTRACAO')
	INSERT INTO #NFECFOPXML VALUES ('916' , 'CONSERTO OU REPARO')
	INSERT INTO #NFECFOPXML VALUES ('917' , 'CONSIGNACAO')
	INSERT INTO #NFECFOPXML VALUES ('919' , 'DEVOLUCAO SIMBOLICA')
	INSERT INTO #NFECFOPXML VALUES ('922' , 'VENDA FUTURA (FATURAMENTO)')
	INSERT INTO #NFECFOPXML VALUES ('923' , 'REMESSA A ORDEM')
	INSERT INTO #NFECFOPXML VALUES ('929' , 'VENDA DE PRODUTOS POR CUPOM FISCAL')
	INSERT INTO #NFECFOPXML VALUES ('933' , 'PRESTACAO DE SERVICO')
	INSERT INTO #NFECFOPXML VALUES ('949' , 'OUTRAS SAIDAS')

	-- SELECT * FROM #NFECFOPXML

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	-- TBS080 TABELA DE AUTORIZAÇÃO

	IF object_id('tempdb.dbo.#TBS080') IS NOT NULL	
		DROP TABLE #TBS080;	
   
	SELECT 
		ENFNUM,
		SNEEMPCOD,
		SNESER,
		ENFTIPDOC,
		ENFFINEMI,
		ENFCODDES,
		ENFCNPJCPF
	INTO #TBS080 FROM TBS080 (NOLOCK)
	WHERE 
		ENFDATEMI BETWEEN @Date_De AND @Date_Ate AND
		ENFSIT = 6 AND 
		ENFTIPDOC = 0 

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	-- TABELA DE FORNECEDORES 

	IF object_id('tempdb.dbo.#TBS006') IS NOT NULL
	   DROP TABLE #TBS006;

	SELECT 
		FORCOD,
		RTRIM(LTRIM(FORNOM)) AS FORNOM,
		MUNCOD,
		FORINDIE,
		FORTIPPES,
		CASE WHEN FORTIPPES = 'F' OR RTRIM(LTRIM(FORIES)) LIKE('ISE%')
			THEN ''
			ELSE RTRIM(LTRIM(FORIES)) 
		END AS FORIES
	INTO #TBS006 FROM TBS006 (NOLOCK)

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	-- TABELA DE CLIENTES 

	IF object_id('tempdb.dbo.#TBS002') IS NOT NULL
	   DROP TABLE #TBS002;

	SELECT 
		CLICOD,
		RTRIM(LTRIM(CLINOM)) AS CLINOM,
		MUNCOD,
		CLIINDIE,
		CLITIPPES,
		CLIIES
	INTO #TBS002 FROM TBS002 (NOLOCK)

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	-- Produtos XML

	IF object_id('tempdb.dbo.#NFEXML') IS NOT NULL
	   DROP TABLE #NFEXML;	

	SELECT
		B.NFEEMPCOD,
		B.NFETIP,
		B.SEREMPCOD,
		B.SERCOD,
		CASE WHEN NFECAN <> 'S'
			THEN 
				CASE WHEN NFEUSUEFE = ''
					THEN 'ABERTO' -- ABERTO
					ELSE 'EFETIVADO' -- EFETIVADO
				END 
			ELSE 'CANCELADO' -- CANCELADO
		END AS OP,
	
		CASE B.NFETIP 
			WHEN 'N' THEN 'COM'
			WHEN 'D' THEN 'DEV'
			WHEN 'T' THEN 'TRA'
			WHEN 'C' THEN 'CPL'
			ELSE ''
		END NFETIPDES,

		CASE NFESUBTIP 
			WHEN 'R' THEN CASE WHEN B.NFETIP = 'N' THEN 'PARA COMERCIALIZACAO' ELSE 'DE CLIENTE REVENDEDOR' END
			WHEN 'U' THEN 'PARA USO E CONSUMO'
			WHEN 'B' THEN 'ENTRADA DE BONIFICACAO,DOACAO OU BRINDE'
			WHEN 'A' THEN 'ENTRADA DE AMOSTRA GRATIS'
			WHEN 'V' THEN 'DE CLIENTE CONSUMIDOR'
			WHEN 'O' THEN 'OUTROS'
			WHEN ''  THEN CASE WHEN B.NFETIP = 'T' THEN 'TRANSFERENCIA' ELSE CASE WHEN B.NFETIP = 'C' THEN 'COMPLEMENTO' ELSE '' END END 
		END NFESUBTIP,

		B.NFECOD,
		ISNULL(CLINOM, FORNOM) AS CLIENTEFORNECEDOR,
		B.NFENUM,
		B.NFEDATEMI,
		B.NFEDATEFE,
		B.NFEESTORI,
		B.NFENOSFOR,
		0 AS LESCOD,
		MIN(A.NFEITE) AS NFEITEXML ,
		A.NFEPROFOR,
		RTRIM(LTRIM(A.NFEDESXML)) AS NFEDESXML,
		A.NFEUMXML,
		A.NFEQTDXML,
		A.NFECALC,
		A.NFEFATOR,
		SUM(A.NFEQTD) AS NFEQTD,
		'' AS NFEMOVEST,
		A.NFECFOPXML,
		ISNULL(G.NFECFOPDES,'') AS NFECFOPDES,
		A.NFEPREXML,
		A.NFEVALPROXML,
		A.NFEVALDESITEXML,
		A.NFEVALFREITEXML,
		A.NFEVALSEGITEXML,
		A.NFEVALOUTITEXML,
		A.NFEBASIPIXML,
		A.NFEPERIPIXML,
		A.NFEVALIPIXML,
		A.NFEBASICMSSTXML,
		A.NFEPERICMSSTXML,
		A.NFEVALICMSSTXML,
		(A.NFEQTDXML * A.NFEPREXML) - A.NFEVALDESITEXML + A.NFEVALFREITEXML + A.NFEVALSEGITEXML + A.NFEVALOUTITEXML + A.NFEVALIPIXML + A.NFEVALICMSSTXML AS NFETOTOPEITEXML,
		A.NFENCMXML,
		A.NFECSTXML,
		CASE WHEN A.NFEVCRESN > 0 
			THEN (A.NFEQTDXML * A.NFEPREXML) - A.NFEVALDESITEXML + A.NFEVALFREITEXML + A.NFEVALSEGITEXML + A.NFEVALOUTITEXML + A.NFEVALIPIXML + A.NFEVALICMSSTXML
			ELSE A.NFEBASICMSXML
		END NFEBASICMSXML,
		A.NFEREDBASICMS,	
		CASE WHEN ISNULL(A.NFEPCRESN,0) > 0 
			THEN A.NFEPCRESN
			ELSE A.NFEPERICMSXML
		END NFEPERICMSXML,
		CASE WHEN ISNULL(A.NFEVCRESNXML,0) > 0 
			THEN A.NFEVCRESNXML
			ELSE A.NFEVALICMSXML
		END NFEVALICMSXML,
		ROW_NUMBER() OVER( PARTITION BY B.NFEEMPCOD, B.NFETIP, B.NFENUM, B.NFECOD, B.SEREMPCOD, B.SERCOD, A.NFEITEXML ORDER BY B.NFEEMPCOD, B.NFETIP, B.NFENUM, B.NFECOD, B.SEREMPCOD, B.SERCOD, A.NFEITE ) AS itemXml
	INTO #NFEXML FROM TBS0591 A (NOLOCK) 
		INNER JOIN TBS059 B (NOLOCK) ON A.NFEEMPCOD = B.NFEEMPCOD AND A.NFECOD = B.NFECOD AND A.NFENUM = B.NFENUM AND A.NFETIP = B.NFETIP AND A.SERCOD = B.SERCOD AND A.SEREMPCOD = B.SEREMPCOD
		LEFT JOIN #TBS080 D (NOLOCK) ON A.NFENUM = D.ENFNUM AND A.NFECOD = D.ENFCODDES
		LEFT JOIN #TBS006 E (NOLOCK) ON B.NFECOD = E.FORCOD AND B.NFETIP NOT IN ('D')
		LEFT JOIN #TBS002 F (NOLOCK) ON B.NFECOD = F.CLICOD AND B.NFETIP IN ('D')
		LEFT JOIN #NFECFOPXML G 	 ON SUBSTRING(A.NFECFOPXML,3,3) COLLATE DATABASE_DEFAULT = G.NFECFOPXML
	WHERE 
		NFEDATEMI BETWEEN @DataEmissao_De AND @DataEmissao_Ate AND
		NFEDATENT BETWEEN @DataEntrada_De AND @DataEntrada_Ate AND
		NFEDATEFE BETWEEN @Date_De AND @Date_Ate AND		
		A.NFETIP IN (SELECT valor FROM #TIPOSNOTA) AND 
		A.NFECOD = CASE WHEN @NFECOD = 0 THEN A.NFECOD ELSE @NFECOD END AND		
		A.NFENUM = CASE WHEN @NFENUM = 0 THEN A.NFENUM ELSE @NFENUM END AND
		A.PROCOD COLLATE DATABASE_DEFAULT IN (SELECT PROCOD FROM #CodigosProduto) AND 
		A.NFEPROFOR = CASE WHEN @CodigoProduto_XML = '' THEN A.NFEPROFOR ELSE @CodigoProduto_XML END AND 
		A.NFEDESXML LIKE(CASE WHEN @Descricao_XML = '' THEN '% %' ELSE @Descricao_XML END) AND 		
		A.NFEMOVEST IN (SELECT valor FROM #MOVEST) AND
		B.NFECAN IN (SELECT valor FROM #CANCEL) AND 
		B.NFENOM LIKE(CASE WHEN @NFENOM = '' THEN B.NFENOM ELSE @NFENOM END ) AND		
		LEN(B.NFEUSUEFE) BETWEEN (CASE WHEN @SeEfetivado = 'T' OR @SeEfetivado = 'N' THEN 0 ELSE 1 END) AND (CASE WHEN @SeEfetivado = 'N' THEN 0 ELSE 50 END) AND
		(D.ENFTIPDOC IS NOT NULL OR (NFENOSFOR <> 'S')) --/*AND B.NFECAN <> 'S' AND NFEDATEFE <> ''*/)) -- TENHO QUE TIRAR ESSE FILTRO QUE ESTÁ ENTRE /* */ PARA QUE EU POSSA FILTRAR AS NOTAS ESTÃO CANCELADAS E EM ABERTO.		
		-- para filtrar tudo preciso comentar movimenta estoque, nota cancelada, efetivação e tipo de nota
	GROUP BY 
		B.NFEEMPCOD,
		B.NFETIP,
		B.SEREMPCOD,
		B.SERCOD,
		NFECAN,
		NFEUSUEFE,
		B.NFESUBTIP,
		B.NFECOD,
		ISNULL(CLINOM, FORNOM),
		B.NFENUM,
		B.NFEDATEMI,
		B.NFEDATEFE,
		B.NFEESTORI,
		B.NFENOSFOR,
		A.NFEITEXML,
		A.NFEPROFOR,
		A.NFEDESXML,
		A.NFEUMXML,
		A.NFEQTDXML,
		A.NFECALC,
		A.NFEFATOR,
		A.NFECFOPXML,
		G.NFECFOPDES,
		A.NFEPREXML,
		A.NFEVALPROXML,
		A.NFEVALDESITEXML,
		A.NFEVALFREITEXML,
		A.NFEVALSEGITEXML,
		A.NFEVALOUTITEXML,
		A.NFEBASIPIXML,
		A.NFEPERIPIXML,
		A.NFEVALIPIXML,
		A.NFEBASICMSSTXML,
		A.NFEPERICMSSTXML,
		A.NFEVALICMSSTXML,
		A.NFENCMXML,
		A.NFECSTXML,
		A.NFEBASICMSXML,
		A.NFEREDBASICMS,
		A.NFEPERICMSXML,
		A.NFEVALICMSXML,
		A.NFEITE,
		A.NFEPCRESN,
		A.NFEVCRESN,
		A.NFEVCRESNXML
	ORDER BY 
		B.NFEDATEFE,
		B.NFENUM,
		A.NFEITEXML

	-- SELECT * FROM #NFEXML  WHERE NFENUM = 19036

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	-- Produto Sistema

	IF object_id('tempdb.dbo.#XMLSIS') IS NOT NULL	
	   DROP TABLE #XMLSIS;

	SELECT 
		'XML' AS SIS,
		*, 
		0 AS NFEPREUNI
	INTO #XMLSIS FROM #NFEXML

	UNION
	SELECT 
		'SIS' AS SIS,
		-- 0 AS RANK,
		B.NFEEMPCOD,
		B.NFETIP,
		B.SEREMPCOD,
		B.SERCOD,
		CASE WHEN B.NFECAN <> 'S'
			THEN 
				CASE WHEN NFEUSUEFE = ''
					THEN 'ABERTO' -- ABERTO
					ELSE 'EFETIVADO' -- EFETIVADO
				END 
			ELSE 'CANCELADO' -- CANCELADO
		END AS OP,
	
		CASE B.NFETIP 
			WHEN 'N' THEN 'COM'
			WHEN 'D' THEN 'DEV'
			WHEN 'T' THEN 'TRA'
			WHEN 'C' THEN 'CPL'
			ELSE ''
		END NFETIPDES,

		CASE A.NFESUBTIPITE 
			WHEN 'R' THEN CASE WHEN B.NFETIP = 'N' THEN 'PARA COMERCIALIZACAO' ELSE 'DE CLIENTE REVENDEDOR' END
			WHEN 'U' THEN 'PARA USO E CONSUMO'
			WHEN 'B' THEN 'ENTRADA DE BONIFICACAO,DOACAO OU BRINDE'
			WHEN 'A' THEN 'ENTRADA DE AMOSTRA GRATIS'
			WHEN 'V' THEN 'DE CLIENTE CONSUMIDOR'
			WHEN 'O' THEN 'OUTROS'
			WHEN ''  THEN CASE WHEN B.NFETIP = 'T' THEN 'TRANSFERENCIA' ELSE CASE WHEN B.NFETIP = 'C' THEN 'COMPLEMENTO' ELSE '' END END 
		END NFESUBTIP,

		B.NFECOD,
		ISNULL(CLINOM, FORNOM) AS CLIENTEFORNECEDOR,
		A.NFENUM,
		B.NFEDATEMI,
		B.NFEDATEFE ,
		B.NFEESTORI,
		B.NFENOSFOR,
		A.LESCOD,
		A.NFEITE AS NFEITEXML ,
		A.PROCOD AS NFEPROFOR,
		RTRIM(LTRIM(A.NFEDES)) AS NFEDESXML,
		A.NFEUNI,
		0 AS NFEQTDXML,
		'' AS NFECALC,
		0 AS NFEFATOR,
		A.NFEQTD AS NFEQTD,
		A.NFEMOVEST,
		A.NFECFOP,
		ISNULL(D.NFECFOPDES,'') COLLATE DATABASE_DEFAULT AS NFECFOPDES,
		A.NFEPRE,
		A.NFEPRE * A.NFEQTD AS NFEPRE,
		A.NFEVALDESITE,
		A.NFEVALFREITE,
		A.NFEVALSEGITE,
		A.NFEVALOUTDES,
		A.NFEBASIPI,
		A.NFEPERIPI,
		A.NFEVALIPI,
		A.NFEBASICMSST,
		A.NFEPERICMSST,
		A.NFEVALICMSST,
		(A.NFEQTD * A.NFEPRE) - A.NFEVALDESITE + A.NFEVALFREITE + A.NFEVALSEGITE + A.NFEVALOUTDES + A.NFEVALIPI + A.NFEVALICMSST AS NFETOTOPEITE,
		A.NFEPRONCM,
		A.NFECST,
		CASE WHEN (A.NFEVALICMSST > 0 AND B.NFETIP NOT IN ('D')) OR SUBSTRING(A.NFECFOP,3,3) IN ('556','557') OR (A.LESCOD = 6 AND SUBSTRING(A.NFECFOP,3,3) IN ('910'))
			THEN 0
			ELSE 
				CASE WHEN A.NFEVCRESN > 0 
					THEN A.NFETOTOPEITE
					ELSE A.NFEBASICMS
				END
		END AS NFEBASICMS, 

		A.NFEREDBASICMS,
		-- (A.NFEQTD * A.NFEPRE) - A.NFEVALDESITE + A.NFEVALFREITE + A.NFEVALOUTDES + A.NFEVALSEGITE - A.NFEBASICMS as VALRED,

		CASE WHEN (A.NFEVALICMSST > 0 AND B.NFETIP NOT IN ('D')) OR SUBSTRING(A.NFECFOP,3,3) IN ('556','557') OR (A.LESCOD = 6 AND SUBSTRING(A.NFECFOP,3,3) IN ('910'))
			THEN 0
			ELSE 
				CASE WHEN NFEPCRESN > 0 
					THEN NFEPCRESN
					ELSE NFEPERICMS
				END
		END AS NFEPERICMS,

		CASE WHEN (A.NFEVALICMSST > 0 AND B.NFETIP NOT IN ('D')) OR SUBSTRING(A.NFECFOP,3,3) IN ('556','557') OR (A.LESCOD = 6 AND SUBSTRING(A.NFECFOP,3,3) IN ('910'))
			THEN 0
			ELSE 
				CASE WHEN NFEVCRESN > 0 
					THEN NFEVCRESN
					ELSE round(A.NFEVALICMS,2)
				END
		END AS NFEVALICMS,
		C.itemXml,
		CASE WHEN A.NFEQTD <> 0 
			THEN CONVERT(DECIMAL(10,4),ROUND(A.NFETOTOPEITE / (A.NFEQTD * CASE WHEN A.NFEQTDEMB = 0 THEN 1 ELSE A.NFEQTDEMB END),4)) 
			ELSE 0
		END AS NFEPREUNI
	FROM TBS0591 A (NOLOCK)
		INNER JOIN TBS059 B (NOLOCK) ON A.NFEEMPCOD = B.NFEEMPCOD AND A.NFECOD = B.NFECOD AND A.NFENUM = B.NFENUM AND A.NFETIP = B.NFETIP AND A.SERCOD = B.SERCOD AND A.SEREMPCOD = B.SEREMPCOD
		INNER JOIN #NFEXML C ON A.NFEEMPCOD = C.NFEEMPCOD AND A.NFECOD = C.NFECOD AND A.NFENUM = C.NFENUM AND A.NFETIP = C.NFETIP AND A.SERCOD = C.SERCOD AND A.SEREMPCOD = C.SEREMPCOD AND A.NFEITE = C.NFEITEXML
		LEFT JOIN #NFECFOP D (NOLOCK) ON SUBSTRING(A.NFECFOP,3,3) COLLATE DATABASE_DEFAULT = D.NFECFOP
		LEFT JOIN #TBS006 E (NOLOCK) ON B.NFECOD = E.FORCOD AND A.NFETIP NOT IN ('D')
		LEFT JOIN #TBS002 F (NOLOCK) ON B.NFECOD = F.CLICOD AND A.NFETIP IN ('D')

	-- select * from #XMLSIS WHERE NFENUM = 19036

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	-- DELETAR TUDO O QUE NÃO TEM XML DA LINHA DO XML

	DELETE #XMLSIS
	WHERE
		SIS = 'XML' AND
		NFETIP = 'D'
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	-- UPDATE NOS ITENS QUE FORAM RATEADOS 

	BEGIN TRAN 
		UPDATE #XMLSIS SET 
		NFEQTD = CASE WHEN NFECALC = 'M' THEN NFEQTDXML * NFEFATOR ELSE CASE WHEN NFECALC = 'D' THEN NFEQTDXML / NFEFATOR ELSE NFEQTD END END 

		FROM #XMLSIS A 
		INNER JOIN (
				SELECT 
				A.NFEEMPCOD,
				A.NFECOD,
				A.NFENUM,
				A.NFETIP,
				A.SERCOD,
				A.SEREMPCOD,
				A.SIS,
				A.NFEPROFOR
		
				FROM #XMLSIS A
		
				WHERE 
				itemXml > 1 AND SIS = 'XML' 
		
				GROUP BY
				A.NFEEMPCOD,
				A.NFECOD,
				A.NFENUM,
				A.NFETIP,
				A.SERCOD,
				A.SEREMPCOD,
				A.SIS, 
				A.NFEPROFOR		) B ON A.NFEEMPCOD = B.NFEEMPCOD AND A.NFECOD = B.NFECOD AND A.NFENUM = B.NFENUM AND A.NFETIP = B.NFETIP AND A.SERCOD = B.SERCOD AND A.SEREMPCOD = B.SEREMPCOD AND A.SIS = B.SIS AND A.NFEPROFOR = B.NFEPROFOR

		WHERE 
		A.itemXml = 1

		-- DELETAR ITENS XML QUE FORAM RATEADOS
		DELETE #XMLSIS 
		WHERE 
			itemXml > 1 AND
			SIS = 'XML'
	COMMIT TRAN 

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	-- CRIAR A TABELA DE ITENS 

	IF object_id('tempdb.dbo.#ITENS') IS NOT NULL
	   DROP TABLE #ITENS;

	SELECT 
		SIS,
		OP,
		NFETIPDES,
		NFESUBTIP,
		NFECOD,
		CLIENTEFORNECEDOR,
		NFENUM,
		NFEDATEMI,
		NFEDATEFE,
		NFEESTORI,
		NFENOSFOR,
		LESCOD,
		NFEITEXML ,
		NFEPROFOR,
		NFEDESXML,
		NFEUMXML,
		NFEQTDXML,
		NFECALC,
		NFEFATOR,
		NFEQTD,
		NFEMOVEST,
		NFECFOPXML,
		NFECFOPDES,
		NFEPREXML,
		NFEVALPROXML,
		NFEVALDESITEXML,
		NFEVALFREITEXML,
		NFEVALSEGITEXML,
		NFEVALOUTITEXML,
		NFEBASIPIXML,
		NFEPERIPIXML,
		NFEVALIPIXML,
		NFEBASICMSSTXML,
		NFEPERICMSSTXML,
		NFEVALICMSSTXML,
		NFETOTOPEITEXML,
		NFENCMXML,
		NFECSTXML,
		NFEBASICMSXML,
		NFEREDBASICMS,
		-- (A.NFEQTDXML * A.NFEPREXML) - A.NFEVALDESITEXML + A.NFEVALFREITEXML + A.NFEVALOUTITEXML + A.NFEVALSEGITEXML - A.NFEBASICMSXML as VALRED,
		NFEPERICMSXML,
		NFEVALICMSXML,
		isnull(B.TDPPRECOR1,0) AS precoVenda,
		isnull(B.TDPCUSBAS,0) AS precoCusto,
		NFEPREUNI
	INTO #ITENS	FROM #XMLSIS A
		LEFT JOIN TBS031 B (NOLOCK) ON 
		A.NFEPROFOR = B.TDPPROCOD
	ORDER BY
		NFEDATEFE,
		NFECOD, 
		NFENUM,
		NFETIPDES,
		NFESUBTIP,
		NFEITEXML,
		SIS DESC 

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	-- CRIAR A TABELA POR NOTA 

	IF object_id('tempdb.dbo.#NOTA') IS NOT NULL
	   DROP TABLE #NOTA;

	SELECT 
		SIS,
		OP,
		NFETIPDES,
		NFESUBTIP,
		NFECOD,
		CLIENTEFORNECEDOR,
		NFENUM,
		NFEDATEMI,
		NFEDATEFE,
		NFEESTORI,
		NFENOSFOR,
		'' AS LESCOD,
		-1 AS NFEITEXML ,
		'' AS NFEPROFOR,
		'' AS NFEDESXML,
		'' AS NFEUMXML,
		0 AS NFEQTDXML,
		'' AS NFECALC,
		0 AS NFEFATOR,
		0 AS NFEQTD,
		'' AS NFEMOVEST,
		'' AS NFECFOPXML,
		'' AS NFECFOPDES,
		0 AS NFEPREXML,
		ROUND(SUM(NFEVALPROXML),2) 		AS NFEVALPROXML,
		ROUND(SUM(NFEVALDESITEXML),2) 	AS NFEVALDESITEXML,
		ROUND(SUM(NFEVALFREITEXML),2) 	AS NFEVALFREITEXML,
		ROUND(SUM(NFEVALSEGITEXML),2) 	AS NFEVALSEGITEXML,
		ROUND(SUM(NFEVALOUTITEXML),2) 	AS NFEVALOUTITEXML,
		ROUND(SUM(NFEBASIPIXML),2)		AS NFEBASIPIXML,

		CASE WHEN ROUND(SUM(NFEBASIPIXML),2) = 0
			THEN 0
			ELSE ROUND(SUM(NFEVALIPIXML),2) / ROUND(SUM(NFEBASIPIXML),2) * 100
		END  AS NFEPERIPIXML,

		ROUND(SUM(NFEVALIPIXML),2)		AS NFEVALIPIXML,
		ROUND(SUM(NFEBASICMSSTXML),2)	AS NFEBASICMSSTXML,

		CASE WHEN ROUND(SUM(NFEBASICMSSTXML),2) = 0
			THEN 0
			ELSE ROUND(SUM(NFEVALICMSSTXML),2) / ROUND(SUM(NFEBASICMSSTXML),2) * 100
		END  AS NFEPERICMSSTXML,

		ROUND(SUM(NFEVALICMSSTXML),2)	AS NFEVALICMSSTXML,
		ROUND(SUM(NFETOTOPEITEXML),2)	AS NFETOTOPEITEXML,
		'' AS NFENCMXML,
		'' AS NFECSTXML,
		ROUND(SUM(NFEBASICMSXML),2)		AS NFEBASICMSXML,
		0 AS NFEREDBASICMS,
		-- (A.NFEQTDXML * A.NFEPREXML) - A.NFEVALDESITEXML + A.NFEVALFREITEXML + A.NFEVALOUTITEXML + A.NFEVALSEGITEXML - A.NFEBASICMSXML as VALRED,
		0 AS NFEPERICMSXML,
		ROUND(SUM(NFEVALICMSXML),2)		AS NFEVALICMSXML,
		0 AS precoVenda,
		0 AS precoCusto,
		0 AS NFEPREUNI
	INTO #NOTA FROM #XMLSIS 

	GROUP BY 
		SIS,
		OP,
		NFETIPDES,
		NFESUBTIP,
		NFECOD,
		CLIENTEFORNECEDOR,
		NFENUM,
		NFEDATEMI,
		NFEDATEFE,
		NFEESTORI,
		NFENOSFOR
	ORDER BY 
		NFEDATEFE,
		NFECOD,
		NFENUM,
		NFETIPDES,
		NFESUBTIP,
		NFEITEXML, 
		SIS DESC 

	-- DELETAR TUDO O QUE NÃO TEM XML DA LINHA DO XML
	DELETE #ITENS
	WHERE 
		NFEDESXML = '' AND
		NFEUMXML = '' AND
		NFEITEXML >= 0 

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	
	-- Tabela final

	SET @QuantidadeNotas = ( select sum(a.qtd) from ( select 1 AS qtd from #NOTA WHERE SIS = 'SIS' GROUP BY OP, NFETIPDES, NFECOD, NFENUM ) as a )
	SET @ValorTotalNotas = (select sum(NFETOTOPEITEXML) from #NOTA WHERE SIS = 'SIS')
	
	SELECT 
		@QuantidadeNotas as QuantidadeNotas, 
		@ValorTotalNotas as ValorTotalNotas, 
		* 
	FROM #NOTA 

	UNION 
	SELECT 
		@QuantidadeNotas as QuantidadeNotas,
		@ValorTotalNotas as ValorTotalNotas, 
		*
	FROM #ITENS
END